services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: legisbot
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
      - ./chroma-db:/app/chroma-db
    restart: unless-stopped
    networks:
      - legisbot-network

  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    container_name: legisbot-ollama
    tty: true
    ports:
      - "11434:11434"
    volumes:
      - legisbot-ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - legisbot-network

volumes:
    legisbot-ollama:

networks:
  legisbot-network:
