services:
  ollama:
    build:
      context: ./docker/ollama
      dockerfile: Dockerfile
    container_name: legisbot-ollama
    tty: true
    ports:
      - "11434:11434"
    volumes:
      - legisbot-ollama:/root/.ollama
    restart: unless-stopped

volumes:
    legisbot-ollama:
