"""alter QA table

Revision ID: e38cb6438233
Revises: 63f63c054301
Create Date: 2025-08-29 16:13:31.242495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e38cb6438233'
down_revision: Union[str, Sequence[str], None] = '63f63c054301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qas', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qas', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
